### ISSUE TITLE
The gem isn't in rubygems.

### ISSUE THREAD

**Issue by belazaras** [toddp/aceroute#1]
Is this possible, could you fix it? Thanks!

**Comment by toddp** [comment]
hi @belazaras , 

It's a pretty rough version, so I haven't published it yet.  I can put it in rubygems if you like. Or you can just install it using the github gem syntax: 

gem 'aceroute', github: 'toddp/aceroute'

**Comment by belazaras** [comment]
Hello yes, i've installed it that way. I could contribute to the gem, but there's no documentation of the AceRoute API, where did you find it?! How do I know how to format the XMLs? Name fields?
Thanks!!

**Comment by toddp** [comment]
I will upload the ace route Ali doc as well as better readme for this gem so it will be clear.  You shouldn't need to use xml with this gem because it converts everything for you. You just need to pass in a gas with the correct parameters which I will describe.

I am away from my computer right now but will do this adapter and let you know when it's updated.

Thanks for getting in touch, you may be the first person to try this gem so I'm eager to hear your feedback!

**Comment by belazaras** [comment]
Great, I'd like to see those docs :D  I know I shouldn't need the XMLs, I said that to contribute expanding the gem.

**Comment by toddp** [comment]
hi @belazaras, I'm working on some documentation for the gem now and will upload it shortly. Thanks for your help!

**Comment by toddp** [comment]
ok @belazaras , I updated a few things: 

readme now has link to https://github.com/toddp/aceroute where the docs are published. 

Docs are done with yardoc, so I commented the code to indicate what the methods do, what parameters are, etc. Let me know if it's not clear.

I've also added the Aceroute API PDF to the docs/ folder if you need to refer to it. You shouldn't need to, so let me know if there's something in there that should be included in my gem documentation.

Also there's a lot I'd like to improve on this gem, but since you are starting to use it I'll be careful about making breaking changes. Again if you have suggestions on how to make it better, let me know. 

Thanks for your support, I'm psyched to have you using this gem. If you'd like to contribute let me know! 

-Todd

**Comment by belazaras** [comment]
Thanks a lot Todd, I've forked the gem and modified a couple things, will check later if it's worth making a pull request or telling what I changed :) See you, Nico.

**Comment by toddp** [comment]
thanks @belazaras, a pull request would be great! Thanks!

**Comment by toddp** [comment]
It's been a long time, but I finally published this gem to RubyGems: 

https://rubygems.org/gems/aceroute

I've started refactoring it to have a class representing each API entity like Customer, Location, etc. So it's a bit more natural to use now.
