### ISSUE TITLE
Schedule

### ISSUE THREAD

**Issue by magmath** [toddp/aceroute#2]
Great job! I am trying to make a scheduling via API, to send a ticket number direct to Ace Route. If you have some tips I´ll appreciate.

**Comment by toddp** [comment]
hi @magmath  -- can you give me some more details on what you are trying to do? I may be able to help.

**Comment by toddp** [comment]
@magmath  try something like this: 

`Aceroute::create_order(odr)
`

where 'odr' is your order hash which contains the necessary fields: 

```

    odr = {
      cid: order.aceroute_customer.cid,
      nm: "Sally Smith", 
      dur: 10,  
      schd: 1,
      start_epoch: start_time,
      lid: order.aceroute_location.id, 
      cntid: 0,
      rid: 10001,
      tid: 0,
      pid: 0, 
      dtl: "3 cases of widgets", 
      po: order.id,
      inv: nil,
      note: ""  #FIXME: someday add notes field to order form
    }
```

some of those fields aren't very descriptive, but they're taken from the Aceroute api docs; I'll attach those here and document them in the README.  To create an Order, you first need to have created an Aceroute Location, and an Aceroute Customer (you can see them referenced in the hash above).  The other fields: 

nm:  Name of customer
dur: duration of the customer visit, in minutes 
schd: ??
start_epoch: time of the delivery to be scheduled, in seconds since the epoch 
lid: location ID (id of Location object in Aceroute for this order)
cntid: ??
rid: ??
tid: ??
pid: ??
dtl:  description of the order
po: "Purchase Order" number for invoicing if any 
inv: ??
note: text note about this order, special delivery instructions, etc

**Comment by belazaras** [comment]
Hello, I wanted to clarify that the start_epoch field is in milliseconds! So if you want the date of Today in Ruby you can use Time.now.to_i \* 1000 :smile:

**Comment by toddp** [comment]
correct, thanks @belazaras  -- I can update the docs to reflect that, or I can change the gem to take in seconds and convert it to milliseconds. I think 'seconds since the epoch' is a pretty standard way of doing it.

**Comment by belazaras** [comment]
Yes, you´re rihgt, seconds are cool! Can you send me the api docs via mail? It's belazaras@live.com. I'd really appreciate that, see you!

**Comment by toddp** [comment]
hi @magmath see the comments I made in the other issue thread; basically I updated the README, and added some API documentation here :  http://toddp.github.io/aceroute/  

hope that helps - let me know if you have specific questions with using the gem and I'll help however I can.

**Comment by toddp** [comment]
I believe we covered this, @belazaras let me know if you still have questions or bugs around this issue. 

And check out the gem I just published, let me know any feedback you have or if you want to contribute!
